version: '3.8'

services:
  nginx:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/sites-available/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/staticfiles:/app/staticfiles
      - ./app/media:/app/media
    networks:
      - webnet

networks:
  webnet: